#!/usr/bin/env bash
# The script Displays the time for 12 horus and 59 minutes.
#   This script Displays hours from 0 to 12
#   This script Displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
